{{$accessKey := DefaultParam .CL2_ACCESS_KEY ""}}

apiVersion: v1
kind: Secret
metadata:
  name: sysdig-agent
  namespace: sysdig-agent-cl2
  labels:
    app: "sysdig-agent"
type: Opaque
data:
 access-key : "{{$accessKey}}"
